%module(directors="1") TapTradeWrapperAPI

%{
	/* 在包装代码中包含头文件 */

#include "iTapAPICommDef.h"  
#include "iTapTradeAPIDataType.h" 
#include "iTapAPIError.h"  	
#include "iTapTradeAPI.h"  
%}
/* turn on director wrapping Callback */
%feature("director") ITapTradeAPINotify;

/* 解析头文件生成包装代码 */

%include "csharp.swg"
%include "carrays.i"
%include "windows.i"
%include "typemaps.i"
%include "arrays_csharp.i"

%typemap(imtype) ITapTrade::TAPIINT32 &iResult "out int"
%typemap(csin) ITapTrade::TAPIINT32 &iResult %{out $csinput%} 
%typemap(cstype) ITapTrade::TAPIINT32 &iResult "out int";

%apply unsigned int *INPUT  { ITapTrade::TAPIUINT32 *sessionID}
%apply unsigned int *OUTPUT { ITapTrade::TAPIUINT32 *sessionID }; 

%typemap(csin) ITapTrade::TAPIUINT32 *sessionID %{out $csinput%} 
%typemap(cstype) ITapTrade::TAPIUINT32 *sessionID "out uint";

%apply char *{ ITapTrade::TAPISTR_50 * };

%include "iTapAPICommDef.h"
%include "iTapTradeAPIDataType.h"
%include "iTapAPIError.h"
%include "iTapTradeAPI.h"

