//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QTapTradeWrapperApi {

public class TapAPICommodityOrderTimeInForceQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICommodityOrderTimeInForceQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICommodityOrderTimeInForceQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPICommodityOrderTimeInForceQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QTapTradeApiPINVOKE.delete_TapAPICommodityOrderTimeInForceQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TapAPICommodity Commodity {
    set {
      QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_set(swigCPtr, TapAPICommodity.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Commodity_get(swigCPtr);
      TapAPICommodity ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPICommodity(cPtr, false);
      return ret;
    } 
  }

  public int Count {
    set {
      QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_set(swigCPtr, value);
    } 
    get {
      int ret = QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_Count_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTimeInForces {
    set {
      QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_set(swigCPtr, value);
    } 
    get {
      string ret = QTapTradeApiPINVOKE.TapAPICommodityOrderTimeInForceQryRsp_OrderTimeInForces_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICommodityOrderTimeInForceQryRsp() : this(QTapTradeApiPINVOKE.new_TapAPICommodityOrderTimeInForceQryRsp(), true) {
  }

}

}
