/* File : example.i */
%module(directors="1") TapQuoteWrapperAPI
%{
#include "TapAPICommDef.h"  
#include "TapQuoteAPIDataType.h" 
#include "TapAPIError.h"  	
#include "TapQuoteAPI.h"  
%}

/* turn on director wrapping Callback */
%feature("director") ITapQuoteAPINotify;

%include "csharp.swg"
%include "carrays.i"
%include "windows.i"
%include "typemaps.i"
%include "arrays_csharp.i"

%apply int { ITapTrade::TAPIUINT32 *sessionID }
%typemap(cstype) ITapTrade::TAPIUINT32 *sessionID "ref int";
%typemap(imtype) TAPIINT32 &iResult "out int"
%typemap(csin) TAPIINT32 &iResult %{out $csinput%} 
%typemap(cstype) TAPIINT32 &iResult "out int";
%apply int { TAPIUINT32 *sessionID }
%typemap(cstype) TAPIUINT32 *sessionID "ref int";
%array_class(double, doubleArray);
%array_class(unsigned long long, longArray);

/*
%array_class(long, longArray);
%apply double *{ TAPIQPRICE					QBidPrice[20] };
%typemap(cstype) TAPIQPRICE					QBidPrice[20] "double[]";
%apply double INPUT[]{ TAPIQPRICE					QBidPrice[20] };

%apply double OUTPUT[]  {TAPIQPRICE					QBidPrice[20]};
%apply int INPUT[]  {TAPIQVOLUME					QBidQty[20]};
%apply double INPUT[]  {TAPIQPRICE					QAskPrice[20]};
%apply int INPUT[]  {TAPIQVOLUME					QAskQty[20]};
*/

%include "TapAPICommDef.h"
%include "TapQuoteAPIDataType.h"
%include "TapAPIError.h"
%include "TapQuoteAPI.h"
