//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QTapQuoteWrapperApi {

public class TapAPIQuoteContractInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteContractInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIQuoteContractInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIQuoteContractInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          QTapQuoteApiPINVOKE.delete_TapAPIQuoteContractInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TapAPIContract Contract {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_Contract_set(swigCPtr, TapAPIContract.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_Contract_get(swigCPtr);
      TapAPIContract ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPIContract(cPtr, false);
      return ret;
    } 
  }

  public char ContractType {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractType_set(swigCPtr, value);
    } 
    get {
      char ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractType_get(swigCPtr);
      return ret;
    } 
  }

  public string QuoteUnderlyingContract {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_QuoteUnderlyingContract_set(swigCPtr, value);
    } 
    get {
      string ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_QuoteUnderlyingContract_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractName {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractName_set(swigCPtr, value);
    } 
    get {
      string ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractName_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractExpDate {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractExpDate_set(swigCPtr, value);
    } 
    get {
      string ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_ContractExpDate_get(swigCPtr);
      return ret;
    } 
  }

  public string LastTradeDate {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_LastTradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_LastTradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public string FirstNoticeDate {
    set {
      QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_FirstNoticeDate_set(swigCPtr, value);
    } 
    get {
      string ret = QTapQuoteApiPINVOKE.TapAPIQuoteContractInfo_FirstNoticeDate_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIQuoteContractInfo() : this(QTapQuoteApiPINVOKE.new_TapAPIQuoteContractInfo(), true) {
  }

}

}
