//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi
{
    /// <summary>
    /// 客户资金调整查询请求结构
    /// </summary>
    public class TapAPIAccountCashAdjustQryReq : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal TapAPIAccountCashAdjustQryReq(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountCashAdjustQryReq obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~TapAPIAccountCashAdjustQryReq()
        {
            Dispose();
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        TapTradeWrapperPINVOKE.delete_TapAPIAccountCashAdjustQryReq(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /// <summary>
        /// 流号
        /// </summary>
        public uint SerialID
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_SerialID_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_SerialID_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 客户资金账号
        /// </summary>
        public string AccountNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_AccountNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_AccountNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 客户属性
        /// </summary>
        public string AccountAttributeNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_AccountAttributeNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_AccountAttributeNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 开始日期 必填
        /// </summary>
        public string BeginDate
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_BeginDate_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_BeginDate_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 结束日期 必填
        /// </summary>
        public string EndDate
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_EndDate_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIAccountCashAdjustQryReq_EndDate_get(swigCPtr);
                return ret;
            }
        }

        public TapAPIAccountCashAdjustQryReq() : this(TapTradeWrapperPINVOKE.new_TapAPIAccountCashAdjustQryReq(), true)
        {
        }

    }

}
