//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi
{
    /// <summary>
    /// 委托流程查询
    /// </summary>
    public class TapAPIOrderProcessQryReq : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal TapAPIOrderProcessQryReq(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderProcessQryReq obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~TapAPIOrderProcessQryReq()
        {
            Dispose();
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        TapTradeWrapperPINVOKE.delete_TapAPIOrderProcessQryReq(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /// <summary>
        /// 服务器标识
        /// </summary>
        public char ServerFlag
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIOrderProcessQryReq_ServerFlag_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIOrderProcessQryReq_ServerFlag_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托编码
        /// </summary>
        public string OrderNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIOrderProcessQryReq_OrderNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIOrderProcessQryReq_OrderNo_get(swigCPtr);
                return ret;
            }
        }

        public TapAPIOrderProcessQryReq() : this(TapTradeWrapperPINVOKE.new_TapAPIOrderProcessQryReq(), true)
        {
        }

    }

}
