//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi
{
    /// <summary>
    /// 港交所做市商双边撤单请求
    /// </summary>
    public class TapAPIOrderMarketDeleteReq : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal TapAPIOrderMarketDeleteReq(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderMarketDeleteReq obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~TapAPIOrderMarketDeleteReq()
        {
            Dispose();
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        TapTradeWrapperPINVOKE.delete_TapAPIOrderMarketDeleteReq(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /// <summary>
        /// 服务器标识
        /// </summary>
        public char ServerFlag
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_ServerFlag_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_ServerFlag_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 买委托号
        /// </summary>
        public string OrderBuyNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_OrderBuyNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_OrderBuyNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 卖委托号
        /// </summary>
        public string OrderSellNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_OrderSellNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketDeleteReq_OrderSellNo_get(swigCPtr);
                return ret;
            }
        }

        public TapAPIOrderMarketDeleteReq() : this(TapTradeWrapperPINVOKE.new_TapAPIOrderMarketDeleteReq(), true)
        {
        }

    }

}
