//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi
{
    /// <summary>
    /// 历史委托查询响应
    /// </summary>
    public class TapAPIHisOrderQryRsp : global::System.IDisposable
    {
        private global::System.Runtime.InteropServices.HandleRef swigCPtr;
        protected bool swigCMemOwn;

        internal TapAPIHisOrderQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn)
        {
            swigCMemOwn = cMemoryOwn;
            swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
        }

        internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIHisOrderQryRsp obj)
        {
            return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
        }

        ~TapAPIHisOrderQryRsp()
        {
            Dispose();
        }

        public virtual void Dispose()
        {
            lock (this)
            {
                if (swigCPtr.Handle != global::System.IntPtr.Zero)
                {
                    if (swigCMemOwn)
                    {
                        swigCMemOwn = false;
                        TapTradeWrapperPINVOKE.delete_TapAPIHisOrderQryRsp(swigCPtr);
                    }
                    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
                }
                global::System.GC.SuppressFinalize(this);
            }
        }
        /// <summary>
        /// 日期
        /// </summary>
        public string Date
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_Date_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_Date_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 客户资金账号
        /// </summary>
        public string AccountNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_AccountNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_AccountNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 交易所编号
        /// </summary>
        public string ExchangeNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ExchangeNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ExchangeNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 品种类型
        /// </summary>
        public char CommodityType
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CommodityType_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CommodityType_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 品种编码类型
        /// </summary>
        public string CommodityNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CommodityNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CommodityNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 合约
        /// </summary>
        public string ContractNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ContractNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ContractNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 执行价格
        /// </summary>
        public string StrikePrice
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StrikePrice_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StrikePrice_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 看张看跌
        /// </summary>
        public char CallOrPutFlag
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 合约2
        /// </summary>
        public string ContractNo2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ContractNo2_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ContractNo2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 执行价格2
        /// </summary>
        public string StrikePrice2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StrikePrice2_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StrikePrice2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 看张看跌2
        /// </summary>
        public char CallOrPutFlag2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag2_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托类型
        /// </summary>
        public char OrderType
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderType_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderType_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托来源
        /// </summary>
        public char OrderSource
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSource_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSource_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托有效类型
        /// </summary>
        public char TimeInForce
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TimeInForce_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TimeInForce_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 有效日期(GTD情况下使用)
        /// </summary>
        public string ExpireTime
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ExpireTime_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ExpireTime_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 是否风险报单
        /// </summary>
        public char IsRiskOrder
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsRiskOrder_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsRiskOrder_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 买入卖出
        /// </summary>
        public char OrderSide
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSide_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSide_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 开平标志
        /// </summary>
        public char PositionEffect
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_PositionEffect_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_PositionEffect_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 开平标志2
        /// </summary>
        public char PositionEffect2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_PositionEffect2_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_PositionEffect2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 询价号
        /// </summary>
        public string InquiryNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_InquiryNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_InquiryNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 投机保值
        /// </summary>
        public char HedgeFlag
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_HedgeFlag_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_HedgeFlag_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托价格
        /// </summary>
        public double OrderPrice
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderPrice_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderPrice_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托价格2，做市商应价使用
        /// </summary>
        public double OrderPrice2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderPrice2_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderPrice2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 触发价格
        /// </summary>
        public double StopPrice
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StopPrice_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_StopPrice_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托数量
        /// </summary>
        public uint OrderQty
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderQty_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderQty_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 最小成交量
        /// </summary>
        public uint OrderMinQty
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMinQty_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMinQty_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 撤单数量
        /// </summary>
        public uint OrderCanceledQty
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderCanceledQty_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderCanceledQty_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 整型参考值
        /// </summary>
        public int RefInt
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefInt_set(swigCPtr, value);
            }
            get
            {
                int ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefInt_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 浮点参考型。
        /// </summary>
        public double RefDouble
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefDouble_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefDouble_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 字符串参考值
        /// </summary>
        public string RefString
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefString_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_RefString_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 服务器标识
        /// </summary>
        public char ServerFlag
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ServerFlag_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ServerFlag_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托编码
        /// </summary>
        public string OrderNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托流水号
        /// </summary>
        public uint OrderStreamID
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderStreamID_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderStreamID_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 上手号
        /// </summary>
        public string UpperNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 上手通道编号
        /// </summary>
        public string UpperChannelNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperChannelNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperChannelNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 本地号
        /// </summary>
        public string OrderLocalNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderLocalNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderLocalNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 上手流号
        /// </summary>
        public uint UpperStreamID
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperStreamID_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_UpperStreamID_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 系统号
        /// </summary>
        public string OrderSystemNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSystemNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderSystemNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 交易所系统号
        /// </summary>
        public string OrderExchangeSystemNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderExchangeSystemNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderExchangeSystemNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 父单系统号
        /// </summary>
        public string OrderParentSystemNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderParentSystemNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderParentSystemNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 下单人
        /// </summary>
        public string OrderInsertUserNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderInsertUserNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderInsertUserNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 下单时间
        /// </summary>
        public string OrderInsertTime
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderInsertTime_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderInsertTime_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 指令下达人
        /// </summary>
        public string OrderCommandUserNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderCommandUserNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderCommandUserNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托更新人
        /// </summary>
        public string OrderUpdateUserNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateUserNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateUserNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托更新时间
        /// </summary>
        public string OrderUpdateTime
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateTime_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateTime_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托状态
        /// </summary>
        public char OrderState
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderState_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderState_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 成交价
        /// </summary>
        public double OrderMatchPrice
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 成交价2
        /// </summary>
        public double OrderMatchPrice2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice2_set(swigCPtr, value);
            }
            get
            {
                double ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 成交量
        /// </summary>
        public uint OrderMatchQty
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 成交量2
        /// </summary>
        public uint OrderMatchQty2
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty2_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty2_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 最后一次操作错误信息码
        /// </summary>
        public uint ErrorCode
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ErrorCode_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ErrorCode_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 错误信息
        /// </summary>
        public string ErrorText
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ErrorText_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_ErrorText_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 是否为录入委托单
        /// </summary>
        public char IsBackInput
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsBackInput_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsBackInput_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 委托成交删除标记
        /// </summary>
        public char IsDeleted
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsDeleted_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsDeleted_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 是否为T+1单
        /// </summary>
        public char IsAddOne
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsAddOne_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_IsAddOne_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 是否T+1有效
        /// </summary>
        public char AddOneIsValid
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_AddOneIsValid_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_AddOneIsValid_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 冰山单最小随机量
        /// </summary>
        public uint MinClipSize
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_MinClipSize_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_MinClipSize_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 冰山单最大随机量
        /// </summary>
        public uint MaxClipSize
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_MaxClipSize_set(swigCPtr, value);
            }
            get
            {
                uint ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_MaxClipSize_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 软件授权号
        /// </summary>
        public string LicenseNo
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_LicenseNo_set(swigCPtr, value);
            }
            get
            {
                string ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_LicenseNo_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 策略单类型	
        /// </summary>
        public char TacticsType
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TacticsType_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TacticsType_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 触发条件
        /// </summary>
        public char TriggerCondition
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TriggerCondition_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TriggerCondition_get(swigCPtr);
                return ret;
            }
        }
        /// <summary>
        /// 触发价格类型
        /// </summary>
        public char TriggerPriceType
        {
            set
            {
                TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TriggerPriceType_set(swigCPtr, value);
            }
            get
            {
                char ret = TapTradeWrapperPINVOKE.TapAPIHisOrderQryRsp_TriggerPriceType_get(swigCPtr);
                return ret;
            }
        }

        public TapAPIHisOrderQryRsp() : this(TapTradeWrapperPINVOKE.new_TapAPIHisOrderQryRsp(), true)
        {
        }

    }

}
