//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi {

public class TapAPIFillInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIFillInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIFillInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIFillInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeWrapperAPIPINVOKE.delete_TapAPIFillInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSide {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeMatchNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchDateTime {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchDateTime {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public double MatchPrice {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchQty {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_MatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDeleted {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsDeleted_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsDeleted_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrencyGroup {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string FeeCurrency {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeValue {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_FeeValue_get(swigCPtr);
      return ret;
    } 
  }

  public char IsManualFee {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsManualFee_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_IsManualFee_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrositionPrice {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ClosePrositionPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperAPIPINVOKE.TapAPIFillInfo_ClosePrositionPrice_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIFillInfo() : this(TapTradeWrapperAPIPINVOKE.new_TapAPIFillInfo(), true) {
  }

}

}
