//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi {

public class TapAPIBillQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIBillQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIBillQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIBillQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeWrapperAPIPINVOKE.delete_TapAPIBillQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TapAPIBillQryReq Reqdata {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_Reqdata_set(swigCPtr, TapAPIBillQryReq.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_Reqdata_get(swigCPtr);
      TapAPIBillQryReq ret = (cPtr == global::System.IntPtr.Zero) ? null : new TapAPIBillQryReq(cPtr, false);
      return ret;
    } 
  }

  public int BillLen {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_BillLen_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_BillLen_get(swigCPtr);
      return ret;
    } 
  }

  public string BillText {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_BillText_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIBillQryRsp_BillText_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIBillQryRsp() : this(TapTradeWrapperAPIPINVOKE.new_TapAPIBillQryRsp(), true) {
  }

}

}
