//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi {

public class TapAPIOrderMarketInsertReq : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderMarketInsertReq(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderMarketInsertReq obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIOrderMarketInsertReq() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeWrapperPINVOKE.delete_TapAPIOrderMarketInsertReq(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string AccountNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char BuyPositionEffect {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_BuyPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_BuyPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char SellPositionEffect {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_SellPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_SellPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderBuyPrice {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderBuyPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderBuyPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderSellPrice {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSellPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSellPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderBuyQty {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderBuyQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderBuyQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderSellQty {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSellQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_OrderSellQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientBuyOrderNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ClientBuyOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ClientBuyOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientSellOrderNo {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ClientSellOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_ClientSellOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public double RefDouble {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefDouble_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefDouble_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public string Remark {
    set {
      TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_Remark_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPIOrderMarketInsertReq_Remark_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderMarketInsertReq() : this(TapTradeWrapperPINVOKE.new_TapAPIOrderMarketInsertReq(), true) {
  }

}

}
