//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperAPI {

public class TapAPIAccountCashAdjustQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountCashAdjustQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountCashAdjustQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPIAccountCashAdjustQryRsp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeWrapperAPIPINVOKE.delete_TapAPIAccountCashAdjustQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string Date {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_Date_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_Date_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CashAdjustType {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustType_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double CashAdjustValue {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustValue_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustValue_get(swigCPtr);
      return ret;
    } 
  }

  public string CashAdjustRemark {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustRemark_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustRemark_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountBank {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountBank_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountBank_get(swigCPtr);
      return ret;
    } 
  }

  public string BankAccount {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_BankAccount_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_BankAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountLWFlag {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountLWFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountLWFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string CompanyBank {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyBank_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyBank_get(swigCPtr);
      return ret;
    } 
  }

  public string InternalBankAccount {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_InternalBankAccount_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_InternalBankAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char CompanyLWFlag {
    set {
      TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyLWFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperAPIPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyLWFlag_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountCashAdjustQryRsp() : this(TapTradeWrapperAPIPINVOKE.new_TapAPIAccountCashAdjustQryRsp(), true) {
  }

}

}
