//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeWrapperApi {

public class TapAPITradeMessage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPITradeMessage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPITradeMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TapAPITradeMessage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeWrapperPINVOKE.delete_TapAPITradeMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint SerialID {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_SerialID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_SerialID_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TMsgValidDateTime {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgValidDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgValidDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string TMsgTitle {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgTitle_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgTitle_get(swigCPtr);
      return ret;
    } 
  }

  public string TMsgContent {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgContent_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgContent_get(swigCPtr);
      return ret;
    } 
  }

  public char TMsgType {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgType_get(swigCPtr);
      return ret;
    } 
  }

  public char TMsgLevel {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgLevel_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_TMsgLevel_get(swigCPtr);
      return ret;
    } 
  }

  public char IsSendBySMS {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_IsSendBySMS_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_IsSendBySMS_get(swigCPtr);
      return ret;
    } 
  }

  public char IsSendByEMail {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_IsSendByEMail_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_IsSendByEMail_get(swigCPtr);
      return ret;
    } 
  }

  public string Sender {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_Sender_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_Sender_get(swigCPtr);
      return ret;
    } 
  }

  public string SendDateTime {
    set {
      TapTradeWrapperPINVOKE.TapAPITradeMessage_SendDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeWrapperPINVOKE.TapAPITradeMessage_SendDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPITradeMessage() : this(TapTradeWrapperPINVOKE.new_TapAPITradeMessage(), true) {
  }

}

}
